services:
  - type: web
    name: bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: ${BOT_TOKEN}
    autoDeploy: true
